### ISSUE TITLE
How do you draw the Fig.4 and Fig.5?

### ISSUE THREAD

**Issue by UltramanSleepless** [UpstageAI/cl4kt#2]
It is a great work, and I want to know what is tool you have used for drawing these two pictures?

**Comment by aporia3517** [comment]
Thank you for your interest. I used matplotlib and seaborn libraries in Python3.

**Comment by swear-1997** [comment]
Very good model idea, there are some issues that I don't quite understand. Can you tell me what the role of the visualizer.py file in the code is? What is the corresponding image in the article? I don't quite understand. What data does # prob: [L, Q] correspond to? Is it convenient to answer? We look forward to your reply
